-- DROP TABLES IF EXISTS
DROP TABLE IF EXISTS GR08_Ciudad CASCADE;
DROP TABLE IF EXISTS GR08_Departamento CASCADE;
DROP TABLE IF EXISTS GR08_Tipo_Dpto CASCADE;
DROP TABLE IF EXISTS GR08_Habitacion CASCADE;
DROP TABLE IF EXISTS GR08_CostoDepto CASCADE;
DROP TABLE IF EXISTS GR08_Reserva CASCADE;
DROP TABLE IF EXISTS GR08_Pago CASCADE;
DROP TABLE IF EXISTS GR08_Tipo_Pago CASCADE;
DROP TABLE IF EXISTS GR08_EstadoLuegoOcupacion CASCADE;
DROP TABLE IF EXISTS GR08_Huesped CASCADE;
DROP TABLE IF EXISTS GR08_Huesped_Reserva CASCADE;
DROP TABLE IF EXISTS GR08_Tipo_Documento CASCADE;
DROP TABLE IF EXISTS GR08_Persona CASCADE;
DROP TABLE IF EXISTS GR08_Comentario CASCADE;

--DROP FUNCTIONS
DROP FUNCTION IF EXISTS TRFN_GR08_CK_CANTIDAD_HABITACIONES() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR08_CK_RESERVA() CASCADE;