-- DROP TABLES IF EXISTS
DROP TABLE IF EXISTS GR08_Ciudad CASCADE;
DROP TABLE IF EXISTS GR08_Imagen_Depto CASCADE;
DROP TABLE IF EXISTS GR08_Departamento CASCADE;
DROP TABLE IF EXISTS GR08_Tipo_Dpto CASCADE;
DROP TABLE IF EXISTS GR08_Habitacion CASCADE;
DROP TABLE IF EXISTS GR08_CostoDepto CASCADE;
DROP TABLE IF EXISTS GR08_Reserva CASCADE;
DROP TABLE IF EXISTS GR08_Pago CASCADE;
DROP TABLE IF EXISTS GR08_Tipo_Pago CASCADE;
DROP TABLE IF EXISTS GR08_EstadoLuegoOcupacion CASCADE;
DROP TABLE IF EXISTS GR08_Huesped CASCADE;
DROP TABLE IF EXISTS GR08_Huesped_Reserva CASCADE;
DROP TABLE IF EXISTS GR08_Tipo_Documento CASCADE;
DROP TABLE IF EXISTS GR08_Persona CASCADE;
DROP TABLE IF EXISTS GR08_Comentario CASCADE;

--DROP FUNCTIONS
DROP FUNCTION IF EXISTS TRFN_GR08_CK_CANTIDAD_HABITACIONES() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR08_CK_RESERVA() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR08_CK_MAX_HUESPEDES() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR08_DEPARTAMENTO_ESTADO(date,int) CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR08_DEPARTAMENTO_BY_FECHA_CIUDAD(date,date,int) CASCADE;

-- DROP VIEWS
DROP VIEW IF EXISTS GR08_RECAUDACION_ULTIMOS_6_MESES CASCADE; 
